### ISSUE TITLE
Dispatch reduce tasks from schema task

### ISSUE THREAD

**Issue by cafca** [p2panda/aquadoggo#219] opened 2022-08-01 18:37 UTC
We are currently materialising all documents, even when we don't even know their schema. We will eventually restrict that and only materialise documents whose schema is available in the schema provider.

Then, when a new schema has been built by the schema task, we need to dispatch a reduce task for every document of that schema we had previously skipped.

That might be a lot of tasks at once! We could quickly go over channel capacity so we will probably need to find another solution for queuing tasks?

**Comment by adzialocha** [comment] 2022-08-01 19:43
I think this is a duplicate of this one: https://github.com/p2panda/aquadoggo/issues/152

**Comment by adzialocha** [comment] 2022-08-01 19:44
> That might be a lot of tasks at once! We could quickly go over channel capacity so we will probably need to find another solution for queuing tasks?

Don't think that this is a problem, we can just increase the capacity to a large number for now :+1:

**Comment by cafca** [comment] 2022-08-01 20:02
This is about a different situation!

**Comment by adzialocha** [comment] 2022-10-31 10:08
> This is about a different situation!

I read the PR title as a feature request (which I think is handled in https://github.com/p2panda/aquadoggo/issues/152) but I assume with this ticket you want to raise a "bottleneck issue" with the channel capacity? Maybe we can change the PR title to something else?

**Comment by adzialocha** [comment] 2023-07-04 14:58
Think this can be closed: We do not accept operations from unknown schemas, so when a new schema gets "enabled" there will be no data yet to materialize in the database.

**Closed by adzialocha** 2023-07-04 14:58 UTC
